In [1]:
import mysql.connector
import pandas as pd
cnx = mysql.connector.connect(
    user="admin",
    password="admin123",
    host="test-db.cze2nnbbx5pc.eu-west-3.rds.amazonaws.com",
    database="prueba"
)
cursor = cnx.cursor()
def make_query(code):
    cursor.execute(code)
    results = cursor.fetchall()
    cnx.commit()
    return(results)
#Definimos una funci√≥n mediante la que ejecutar las querys devolviendo un dataframe
def make_query_dataframe(code):
    cursor.execute(code)
    results = cursor.fetchall()
    column_names = [desc[0] for desc in cursor.description]  # Obtener los nombres de las columnas
    df = pd.DataFrame(results, columns=column_names)  # Crear el DataFrame
    return df
datos_base_datos=make_query_dataframe("SELECT * FROM prueba.employee_raw;")

  months_left
0        9.00
1        8.00
2        5.00
3       17.00
4       33.00

In [2]:
import plotly.graph_objects as go
import plotly.express as px
df=make_query_dataframe("SELECT months_left from predictions")
# Supongamos que tienes un dataframe llamado "df" con una columna llamada "column_name"
column_name = df['months_left'].astype(float)
# Calcula los cuartiles utilizando la funci√≥n quantile()
q1 = column_name.quantile(0.25)
q2 = column_name.quantile(0.5)
q3 = column_name.quantile(0.75)
# Cuenta el n√∫mero de valores en cada cuartil
count_q1 = column_name[column_name <= q1].count()
count_q2 = column_name[(column_name > q1) & (column_name <= q2)].count()
count_q3 = column_name[(column_name > q2) & (column_name <= q3)].count()
count_q4 = column_name[column_name > q3].count()
column1=["Low","Medium","High","Very High"]
column2=[count_q1,count_q2,count_q3,count_q4]
data = {"risk": column1, "data": column2}
df = pd.DataFrame(data)
df['percentage'] = (df['data'] / df['data'].sum()) * 100
count_values = df.set_index('risk')['data']
colors = {
    "Low": "#00CC96",
    "Medium": "#B6E880",
    "High": "#FFA15A",
    "Very High": "#EF553B"
}

fig = go.Figure(data=[go.Pie(labels=count_values.index, values=count_values.values, hole=0.4, pull=[0.05, 0.05, 0.05, 0.05])])

fig.update_traces(
    marker=dict(colors=[colors[label] for label in count_values.index]),
    textfont=dict(size=22)  # Aumentar el tama√±o de los valores
)

fig.update_layout(
    title="Distribution Risk Attrition",
    title_font=dict(size=24),
    legend=dict(
        orientation="h",
        yanchor="bottom",
        y=1.02,
        xanchor="center",
        x=0.5,
        traceorder='normal'
    )
)

fig.show()

        risk  data  percentage
0        Low   965   26.095187
1     Medium   938   25.365062
2       High   942   25.473229
3  Very High   853   23.066522

In [45]:
employess_actuales=datos_base_datos[datos_base_datos["attrition"]=="No"].copy()
employess_actuales=employess_actuales.drop(columns="id_employee").reset_index().drop(columns="index").reset_index().rename(columns={'index': 'id_employee'})
employess_actuales

,id_employee,name,hours,involvement,performance,environment,satisfaction,life_balance,age,attrition,...,marital_status,income,previous_companies,salary_hike,stock_option,total_working_years,training_ly,years_company,last_promotion,years_curr_manager
0,0,Jennifer Grant,7.32,High,Excellent,High,Very High,Good,51,No,...,Married,131160,1,11,0,1,6,1,0,0
1,1,Joel Rodgers,6.79,High,Excellent,Medium,Medium,Bad,32,No,...,Married,193280,1,15,3,5,2,5,0,3
2,2,Gabriel Henson PhD,7.88,Medium,Excellent,Very High,Very High,Better,38,No,...,Married,83210,3,11,3,13,5,8,7,5
3,3,James Bryant,10.28,High,Excellent,Very High,Low,Better,32,No,...,Single,23420,4,12,2,9,2,6,0,4
4,4,Michelle Wade,6.45,High,Excellent,High,Medium,Good,46,No,...,Married,40710,3,13,0,28,5,7,7,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3693,3693,Rebecca Carlson,8.32,Medium,Excellent,High,Very High,Better,29,No,...,Single,35390,1,18,0,6,2,6,1,5
3694,3694,Kimberly Tucker,5.90,High,Excellent,Very High,Low,Better,42,No,...,Single,60290,3,17,1,10,5,3,0,2
3695,3695,Warren Phillips,7.15,Medium,Excellent,Very High,Very High,Better,29,No,...,Divorced,26790,2,15,0,10,2,3,0,2
3696,3696,Brendan Brown,9.19,High,Outstanding,Low,High,Better,25,No,...,Married,37020,0,20,0,5,4,4,1,2
3697,3697,Troy Rivera,6.51,Medium,Excellent,Very High,Low,Better,42,No,...,Divorced,23980,0,14,1,10,2,9,7,8

In [48]:
make_query("""CREATE TABLE current_employees (
    id_employee INT,
    name VARCHAR(50),
    hours DECIMAL(4,2),
    involvement VARCHAR(50),
    performance VARCHAR(50),
    environment VARCHAR(50),
    satisfaction VARCHAR(50),
    life_balance VARCHAR(50),
    age INT,
    attrition VARCHAR(50),
    travel VARCHAR(50),
    department VARCHAR(50),
    distance_home INT,
    education VARCHAR(50),
    education_field VARCHAR(50),
    gender VARCHAR(50),
    job_level INT,
    role VARCHAR(50),
    marital_status VARCHAR(50),
    income INT,
    previous_companies INT,
    salary_hike INT,
    stock_option INT,
    total_working_years INT,
    training_ly INT,
    years_company INT,
    last_promotion INT,
    years_curr_manager INT,
    PRIMARY KEY (id_employee))"""
)

[]

In [49]:
# Cargar los datos del CSV a la tabla
for row in employess_actuales.itertuples(index=False):
    values = ', '.join("'" + str(value).replace("'", "''") + "'" for value in row)
    query = f"INSERT INTO current_employees VALUES ({values})"
    cursor.execute(query)
    print(row)
# Confirmar los cambios en la base de datos
cnx.commit()
# Cerrar el cursor y la conexi√≥n
cursor.close()
cnx.close()

Pandas(id_employee=0, name='Jennifer Grant', hours=Decimal('7.32'), involvement='High', performance='Excellent', environment='High', satisfaction='Very High', life_balance='Good', age=51, attrition='No', travel='Travel_Rarely', department='Sales', distance_home=6, education='College', education_field='Life Sciences', gender='Female', job_level=1, role='Healthcare Representative', marital_status='Married', income=131160, previous_companies=1, salary_hike=11, stock_option=0, total_working_years=1, training_ly=6, years_company=1, last_promotion=0, years_curr_manager=0)
Pandas(id_employee=1, name='Joel Rodgers', hours=Decimal('6.79'), involvement='High', performance='Excellent', environment='Medium', satisfaction='Medium', life_balance='Bad', age=32, attrition='No', travel='Travel_Frequently', department='Research & Development', distance_home=17, education='Master', education_field='Other', gender='Male', job_level=4, role='Sales Executive', marital_status='Married', income=193280, previous_companies=1, salary_hike=15, stock_option=3, total_working_years=5, training_ly=2, years_company=5, last_promotion=0, years_curr_manager=3)
Pandas(id_employee=2, name='Gabriel Henson PhD', hours=Decimal('7.88'), involvement='Medium', performance='Excellent', environment='Very High', satisfaction='Very High', life_balance='Better', age=38, attrition='No', travel='Non-Travel', department='Research & Development', distance_home=2, education='Doctor', education_field='Life Sciences', gender='Male', job_level=3, role='Human Resources', marital_status='Married', income=83210, previous_companies=3, salary_hike=11, stock_option=3, total_working_years=13, training_ly=5, years_company=8, last_promotion=7, years_curr_manager=5)
Pandas(id_employee=3, name='James Bryant', hours=Decimal('10.28'), involvement='High', performance='Excellent', environment='Very High', satisfaction='Low', life_balance='Better', age=32, attrition='No', travel='Travel_Rarely', department='Research & Development', distance_home=10, education='Below College', education_field='Medical', gender='Male', job_level=1, role='Sales Executive', marital_status='Single', income=23420, previous_companies=4, salary_hike=12, stock_option=2, total_working_years=9, training_ly=2, years_company=6, last_promotion=0, years_curr_manager=4)
Pandas(id_employee=4, name='Michelle Wade', hours=Decimal('6.45'), involvement='High', performance='Excellent', environment='High', satisfaction='Medium', life_balance='Good', age=46, attrition='No', travel='Travel_Rarely', department='Research & Development', distance_home=8, education='Bachelor', education_field='Life Sciences', gender='Female', job_level=4, role='Research Director', marital_status='Married', income=40710, previous_companies=3, salary_hike=13, stock_option=0, total_working_years=28, training_ly=5, years_company=7, last_promotion=7, years_curr_manager=7)
Pandas(id_employee=5, name='Noah Harris', hours=Decimal('6.68'), involvement='High', performance='Outstanding', environment='Low', satisfaction='Medium', life_balance='Better', age=29, attrition='No', travel='Travel_Rarely', department='Research & Development', distance_home=18, education='Bachelor', education_field='Life Sciences', gender='Male', job_level=2, role='Sales Executive', marital_status='Married', income=31430, previous_companies=2, salary_hike=22, stock_option=3, total_working_years=10, training_ly=2, years_company=0, last_promotion=0, years_curr_manager=0)
Pandas(id_employee=6, name='Tyler Henderson', hours=Decimal('6.65'), involvement='High', performance='Outstanding', environment='Medium', satisfaction='Very High', life_balance='Better', age=31, attrition='No', travel='Travel_Rarely', department='Research & Development', distance_home=1, education='Bachelor', education_field='Life Sciences', gender='Male', job_level=3, role='Laboratory Technician', marital_status='Married', income=20440, previous_companies=0, salary_hike=21, stock_option=0, total_working_years=10, training_ly=2, years_company=9, last_promotion=7, years_curr_manager=8)
Pandas(id_employee=7, name='Jasmine Hayes', hours=Decimal('8.13'), involvement='High', performance='Excellent', environment='Medium', satisfaction='Low', life_balance='Better', age=25, attrition='No', travel='Non-Travel', department='Research & Development', distance_home=7, education='Master', education_field='Medical', gender='Female', job_level=4, role='Laboratory Technician', marital_status='Divorced', income=134640, previous_companies=1, salary_hike=13, stock_option=1, total_working_years=6, training_ly=2, years_company=6, last_promotion=1, years_curr_manager=5)
Pandas(id_employee=8, name='Brandon Buchanan', hours=Decimal('6.84'), involvement='Medium', performance='Excellent', environment='High', satisfaction='Very High', life_balance='Better', age=45, attrition='No', travel='Travel_Rarely', department='Research & Development', distance_home=17, education='College', education_field='Medical', gender='Male', job_level=2, role='Laboratory Technician', marital_status='Married', income=79910, previous_companies=0, salary_hike=13, stock_option=2, total_working_years=21, training_ly=2, years_company=20, last_promotion=4, years_curr_manager=10)
Pandas(id_employee=9, name='Robert Aguirre', hours=Decimal('8.55'), involvement='High', performance='Excellent', environment='nan', satisfaction='Very High', life_balance='Better', age=36, attrition='No', travel='Travel_Rarely', department='Research & Development', distance_home=28, education='Below College', education_field='Life Sciences', gender='Male', job_level=1, role='Laboratory Technician', marital_status='Married', income=33770, previous_companies=0, salary_hike=12, stock_option=2, total_working_years=16, training_ly=2, years_company=15, last_promotion=10, years_curr_manager=11)
Pandas(id_employee=10, name='Nicole Rosales', hours=Decimal('8.87'), involvement='High', performance='Excellent', environment='Very High', satisfaction='Low', life_balance='Better', age=55, attrition='No', travel='Travel_Rarely', department='Research & Development', distance_home=14, education='Master', education_field='Life Sciences', gender='Female', job_level=1, role='Sales Executive', marital_status='Single', income=55380, previous_companies=0, salary_hike=17, stock_option=0, total_working_years=37, training_ly=2, years_company=36, last_promotion=4, years_curr_manager=13)
Pandas(id_employee=11, name='William Pham', hours=Decimal('6.38'), involvement='High', performance='Excellent', environment='Very High', satisfaction='Very High', life_balance='Good', age=28, attrition='No', travel='Travel_Rarely', department='Research & Development', distance_home=1, education='Bachelor', education_field='Life Sciences', gender='Male', job_level=1, role='Manufacturing Director', marital_status='Married', income=25920, previous_companies=1, salary_hike=14, stock_option=0, total_working_years=5, training_ly=2, years_company=5, last_promotion=0, years_curr_manager=4)
Pandas(id_employee=12, name='Nicholas Parker', hours=Decimal('6.03'), involvement='High', performance='Excellent', environment='High', satisfaction='Very High', life_balance='Best', age=37, attrition='No', travel='Travel_Rarely', department='Research & Development', distance_home=1, education='Bachelor', education_field='Life Sciences', gender='Male', job_level=2, role='Healthcare Representative', marital_status='Married', income=53460, previous_companies=4, salary_hike=11, stock_option=0, total_working_years=7, training_ly=2, years_company=5, last_promotion=0, years_curr_manager=1)
Pandas(id_employee=13, name='Michael Chen', hours=Decimal('10.88'), involvement='Medium', performance='Excellent', environment='Very High', satisfaction='High', life_balance='Best', age=21, attrition='No', travel='Travel_Rarely', department='Research & Development', distance_home=3, education='College', education_field='Life Sciences', gender='Male', job_level=1, role='Laboratory Technician', marital_status='Single', income=42130, previous_companies=1, salary_hike=12, stock_option=3, total_working_years=3, training_ly=3, years_company=3, last_promotion=1, years_curr_manager=0)
Pandas(id_employee=14, name='Joshua Villarreal', hours=Decimal('6.49'), involvement='High', performance='Excellent', environment='Low', satisfaction='Very High', life_balance='Better', age=37, attrition='No', travel='Non-Travel', department='Research & Development', distance_home=1, education='Bachelor', education_field='Medical', gender='Male', job_level=2, role='Sales Executive', marital_status='Divorced', income=41270, previous_companies=2, salary_hike=13, stock_option=1, total_working_years=15, training_ly=2, years_company=5, last_promotion=0, years_curr_manager=2)
Pandas(id_employee=15, name='Christopher Larson', hours=Decimal('8.62'), involvement='Medium', performance='Excellent', environment='Medium', satisfaction='Medium', life_balance='Good', age=35, attrition='No', travel='Travel_Rarely', department='Sales', distance_home=7, education='Master', education_field='Life Sciences', gender='Male', job_level=1, role='Sales Representative', marital_status='Divorced', income=24380, previous_companies=7, salary_hike=16, stock_option=0, total_working_years=10, training_ly=5, years_company=7, last_promotion=6, years_curr_manager=2)
Pandas(id_employee=16, name='Janet Smith', hours=Decimal('7.07'), involvement='High', performance='Excellent', environment='Low', satisfaction='Low', life_balance='Better', age=38, attrition='No', travel='Travel_Rarely', department='Research & Development', distance_home=8, education='Bachelor', education_field='Life Sciences', gender='Female', job_level=1, role='Manager', marital_status='Divorced', income=68700, previous_companies=1, salary_hike=11, stock_option=1, total_working_years=8, training_ly=5, years_company=8, last_promotion=7, years_curr_manager=7)
Pandas(id_employee=17, name='Jason Browning', hours=Decimal('5.62'), involvement='High', performance='Excellent', environment='High', satisfaction='Medium', life_balance='Bad', age=26, attrition='No', travel='Travel_Frequently', department='Research & Development', distance_home=1, education='Master', education_field='Other', gender='Male', job_level=2, role='Laboratory Technician', marital_status='Divorced', income=104470, previous_companies=1, salary_hike=18, stock_option=0, total_working_years=6, training_ly=3, years_company=6, last_promotion=1, years_curr_manager=4)
Pandas(id_employee=18, name='Christopher Yang', hours=Decimal('7.83'), involvement='Medium', performance='Outstanding', environment='Low', satisfaction='Medium', life_balance='Good', age=50, attrition='No', travel='Travel_Rarely', department='Sales', distance_home=8, education='Master', education_field='Life Sciences', gender='Male', job_level=1, role='Research Scientist', marital_status='Divorced', income=96670, previous_companies=3, salary_hike=23, stock_option=0, total_working_years=28, training_ly=2, years_company=10, last_promotion=1, years_curr_manager=6)
Pandas(id_employee=19, name='Jessica Novak', hours=Decimal('6.62'), involvement='High', performance='Excellent', environment='High', satisfaction='High', life_balance='Good', age=53, attrition='No', travel='Travel_Rarely', department='Research & Development', distance_home=11, education='Master', education_field='Life Sciences', gender='Female', job_level=2, role='Research Scientist', marital_status='Married', income=21480, previous_companies=3, salary_hike=11, stock_option=0, total_working_years=21, training_ly=2, years_company=5, last_promotion=1, years_curr_manager=3)
Pandas(id_employee=20, name='Paul Thompson', hours=Decimal('6.58'), involvement='Low', performance='Excellent', environment='Medium', satisfaction='High', life_balance='Better', age=42, attrition='No', travel='Travel_Rarely', department='Research & Development', distance_home=4, education='Master', education_field='Life Sciences', gender='Male', job_level=1, role='Manufacturing Director', marital_status='Married', income=89260, previous_companies=1, salary_hike=14, stock_option=0, total_working_years=0, training_ly=4, years_company=20, last_promotion=11, years_curr_manager=6)
Pandas(id_employee=21, name='Eric Moore', hours=Decimal('9.06'), involvement='High', performance='Excellent', environment='Medium', satisfaction='Very High', life_balance='Good', age=29, attrition='No', travel='Travel_Frequently', department='Research & Development', distance_home=16, education='Master', education_field='Medical', gender='Male', job_level=1, role='Laboratory Technician', marital_status='Single', income=65130, previous_companies=1, salary_hike=11, stock_option=1, total_working_years=10, training_ly=2, years_company=10, last_promotion=0, years_curr_manager=9)
Pandas(id_employee=22, name='Nicole Harmon', hours=Decimal('10.54'), involvement='High', performance='Excellent', environment='Medium', satisfaction='Very High', life_balance='Better', age=55, attrition='No', travel='Travel_Rarely', department='Research & Development', distance_home=1, education='Master', education_field='Other', gender='Female', job_level=1, role='Research Scientist', marital_status='Married', income=67990, previous_companies=3, salary_hike=11, stock_option=0, total_working_years=12, training_ly=2, years_company=10, last_promotion=0, years_curr_manager=8)
Pandas(id_employee=23, name='Melissa Peterson', hours=Decimal('7.21'), involvement='High', performance='Outstanding', environment='Low', satisfaction='Low', life_balance='Better', age=26, attrition='No', travel='Travel_Frequently', department='Research & Development', distance_home=9, education='Bachelor', education_field='Life Sciences', gender='Female', job_level=1, role='Manager', marital_status='Married', income=162910, previous_companies=1, salary_hike=22, stock_option=0, total_working_years=5, training_ly=3, years_company=5, last_promotion=3, years_curr_manager=3)
Pandas(id_employee=24, name='Gregory Valdez IV', hours=Decimal('10.71'), involvement='High', performance='Excellent', environment='Very High', satisfaction='Very High', life_balance='Better', age=37, attrition='No', travel='Travel_Rarely', department='Sales', distance_home=5, education='Below College', education_field='Marketing', gender='Male', job_level=1, role='Research Scientist', marital_status='Single', income=27050, previous_companies=1, salary_hike=11, stock_option=0, total_working_years=17, training_ly=2, years_company=17, last_promotion=5, years_curr_manager=7)
Pandas(id_employee=25, name='Sara Aguilar', hours=Decimal('9.66'), involvement='Medium', performance='Excellent', environment='Very High', satisfaction='Very High', life_balance='Better', age=38, attrition='No', travel='Travel_Rarely', department='Sales', distance_home=2, education='Bachelor', education_field='Marketing', gender='Female', job_level=1, role='Manager', marital_status='Divorced', income=44480, previous_companies=9, salary_hike=12, stock_option=0, total_working_years=10, training_ly=3, years_company=2, last_promotion=1, years_curr_manager=2)
Pandas(id_employee=26, name='Hayden Matthews', hours=Decimal('9.88'), involvement='Medium', performance='Excellent', environment='Very High', satisfaction='Very High', life_balance='Better', age=28, attrition='No', travel='Travel_Rarely', department='Research & Development', distance_home=7, education='Bachelor', education_field='Other', gender='Male', job_level=1, role='Human Resources', marital_status='Single', income=96370, previous_companies=1, salary_hike=13, stock_option=0, total_working_years=5, training_ly=6, years_company=5, last_promotion=0, years_curr_manager=2)
Pandas(id_employee=27, name='Emily Bradley', hours=Decimal('6.03'), involvement='High', performance='Excellent', environment='High', satisfaction='Low', life_balance='Better', age=49, attrition='No', travel='Travel_Frequently', department='Research & Development', distance_home=1, education='Below College', education_field='Medical', gender='Female', job_level=2, role='Research Scientist', marital_status='Single', income=35910, previous_companies=9, salary_hike=13, stock_option=0, total_working_years=22, training_ly=2, years_company=3, last_promotion=1, years_curr_manager=2)
Pandas(id_employee=28, name='Daniel Harris', hours=Decimal('6.35'), involvement='High', performance='Excellent', environment='High', satisfaction='Medium', life_balance='Better', age=36, attrition='No', travel='Travel_Rarely', department='Sales', distance_home=5, education='Bachelor', education_field='Technical Degree', gender='Male', job_level=3, role='Sales Executive', marital_status='Single', income=54050, previous_companies=4, salary_hike=14, stock_option=0, total_working_years=10, training_ly=2, years_company=8, last_promotion=7, years_curr_manager=7)
Pandas(id_employee=29, name='Dr. Ian Watson', hours=Decimal('9.57'), involvement='High', performance='Excellent', environment='Very High', satisfaction='Medium', life_balance='Good', age=31, attrition='No', travel='Travel_Frequently', department='Research & Development', distance_home=9, education='Master', education_field='Medical', gender='Male', job_level=1, role='Sales Executive', marital_status='Divorced', income=46840, previous_companies=1, salary_hike=16, stock_option=1, total_working_years=2, training_ly=4, years_company=2, last_promotion=2, years_curr_manager=2)
Pandas(id_employee=30, name='Elijah Mahoney', hours=Decimal('5.52'), involvement='High', performance='Excellent', environment='Medium', satisfaction='Very High', life_balance='Good', age=37, attrition='No', travel='Travel_Frequently', department='Sales', distance_home=9, education='Below College', education_field='Marketing', gender='Male', job_level=1, role='Laboratory Technician', marital_status='Married', income=15140, previous_companies=1, salary_hike=14, stock_option=0, total_working_years=4, training_ly=3, years_company=4, last_promotion=1, years_curr_manager=2)
Pandas(id_employee=31, name='Robert Ramirez', hours=Decimal('6.18'), involvement='High', performance='Excellent', environment='High', satisfaction='Medium', life_balance='Best', age=42, attrition='No', travel='Travel_Frequently', department='Sales', distance_home=2, education='College', education_field='Marketing', gender='Male', job_level=3, role='Research Director', marital_status='Married', income=29560, previous_companies=5, salary_hike=13, stock_option=0, total_working_years=23, training_ly=2, years_company=20, last_promotion=4, years_curr_manager=8)
Pandas(id_employee=32, name='Steve Baldwin', hours=Decimal('7.06'), involvement='Medium', performance='Excellent', environment='High', satisfaction='Medium', life_balance='Good', age=35, attrition='No', travel='Travel_Rarely', department='Sales', distance_home=20, education='College', education_field='Life Sciences', gender='Male', job_level=1, role='Laboratory Technician', marital_status='Married', income=51540, previous_companies=0, salary_hike=19, stock_option=0, total_working_years=12, training_ly=2, years_company=11, last_promotion=6, years_curr_manager=9)
Pandas(id_employee=33, name='Erica Rich', hours=Decimal('7.17'), involvement='Medium', performance='Excellent', environment='High', satisfaction='nan', life_balance='Better', age=36, attrition='No', travel='Travel_Frequently', department='Research & Development', distance_home=8, education='Bachelor', education_field='Other', gender='Female', job_level=3, role='Sales Executive', marital_status='Married', income=69620, previous_companies=4, salary_hike=12, stock_option=2, total_working_years=4, training_ly=2, years_company=1, last_promotion=0, years_curr_manager=0)